### PR TITLE
make the footer slightly bigger

### PR DESCRIPTION
**Pull request by siteshwar**
... to make it easier to read.

### CODE REVIEW

**Comment by siteshwar** [comment]
Current default size of the footer may be too hard for some users to read. It can be seen on the [Fedora deployment](https://openscanhub.fedoraproject.org/).



This is a screenshot from OpenScanHub with the requested change:

screenshot

**Review by lzaoral — CHANGES_REQUESTED** [review]
@siteshwar I'm don't think that the text in a footer should be bigger than the actual main text in menus or the main content as shown in your picture.

edit: Of course, I agree that the current text size is too small.

**Comment by siteshwar** [comment]
@rohanpm Would it be possible for you to comment on it?

**Comment by siteshwar** [comment]
> > @siteshwar I'm don't think that the text in a footer should be bigger than the actual main text in menus or the main content as shown in your picture.
> 
> I can set `font-size: 85%;` for the footer. I need somebody else to clarify what would be an acceptable size for it.

I have set it to 85% for now.

**Comment by siteshwar** [comment]
@rohanpm Can we merge this?

**Comment by siteshwar** [comment]
Closing in favor of https://github.com/openscanhub/openscanhub/pull/291

**Pull request closed without merging**
