### PR TITLE
Add tests covering log view

### PR DESCRIPTION
**Pull request by rohanpm**
- Add tox for running tests
- Fix some test failures
- Fix minor bugs which blocked testing
- Add tests for log view

The log view needs an update to fix performance issues when dealing with
large log files.  This PR aims to cover the view with autotests before working
on the performance improvements.

### CODE REVIEW

**Comment by lubomir** [comment]
Do the tests pass for you on py2.6? I tried running them and I'm getting errors. For Django 1.6 in the actual test (`ValueError: zero length field name in format`), for Django 1.8 somewhere deeper in Django (`{…}` is used as a set literal).

**Comment by rohanpm** [comment]
Actually I haven't been able to run them yet for 2.6, but I will do that and squash any failures.

**Comment by rohanpm** [comment]
Updated change now passed with py 2.6 on RHEL6 and py 2.7 on RHEL7.

**Comment by rohanpm** [comment]
@mztahir @midnightercz @tyroneabdy @rbikar @mtyson01 @bmcivor

**Pull request merged**
